repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff-format
        args: [--check]

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        exclude: migrations/
        name: isort (check only)
        args: [--check-only, --diff]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx]
        exclude: ^src/config/static/vendor/
        additional_dependencies:
          - prettier@3.1.0
